language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
# command to install dependencies
install: "pip install -r requirements.txt"

addons:
  browserstack:
    username: "shikhadubey1"
    access_key: "Mhtt1XkQq18k8nqQzsqn"
    
    #trying stuff
